apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260611-155128-l56ob49q2q21-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260611-155128-l56ob49q2q21.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260611-155128-l56ob49q2q21-service
            port:
              number: 80
