apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260611-155128-l56ob49q2q21-service
spec:
  selector:
    app: enterprise-system-20260611-155128-l56ob49q2q21
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
